print("####################################")
print("#                                  #")
print("#  Fadhil Syahdama Mahatama Putra  #")
print("#          2410817210026           #")
print("#                                  #")
print("####################################")